version: "3"
services:
  db:
    image: 'postgres:latest'
    container_name: db
    volumes:
      - ./server/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: db

  server:
    build: ./server
    container_name: server
    ports:
      - "3001:3001"
    networks:
      - my_network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/postgres
    depends_on:
      - db

  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - server

networks:
  my_network:
    driver: bridge